repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
      - id: sqlfmt
        name: sqlfmt
        entry: uv run sqlfmt
        language: system
        types: [sql]
