name: aej
version: 0.1.0
config-version: 2

profile: aej

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

on-run-start: "{{ configure_ci_dataset() }}"

models:
  aej:
    staging:
      +materialized: view
      analytics_engineering_jobs:
        +access: private
        +group: site_content
      resend:
        +access: private
        +group: email
      sendgrid:
        +access: private
        +group: email
      netlify:
        +access: private
        +group: web_engagement
      webflow:
        +access: private
        +group: web_engagement
    intermediate:
      +materialized: view
      email:
        +access: private
        +group: email
    marts:
      +access: public
      +contract:
        enforced: true
      +materialized: table
  ga4:
    staging:
      base:
        base_ga4__events:
          +full_refresh: false # to avoid recombining the source properties, data shouldn't change anyways, can be toggled off as necessary
        base_ga4__users:
          +full_refresh: false # see above under base_ga4__events

vars:
  ga4:
    source_project: "analytics-engineering-jobs"
    combined_dataset: "ga4_combined"
    property_ids: [
      333655999,
      466027950
    ]
    start_date: "20220101"
    static_incremental_days: 7
