#!/usr/bin/env bash
set -euo pipefail

export SERVICE_ACCOUNT_JSON="${SERVICE_ACCOUNT_JSON:-{}}"
export GCP_PROJECT_ID="${GCP_PROJECT_ID:-x}"
export DBT_USER="${DBT_USER:-x}"
export PR_NUMBER="${PR_NUMBER:-0}"

dbt deps --profiles-dir "${1:-.}"
