#!/usr/bin/env bash
set -euo pipefail

install_dir="${1:-/usr/local/bin}"
export SHELL="${SHELL:-/bin/bash}"

version="2.0.0-preview.199"

curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh \
  | sh -s -- --version "$version" --to "$install_dir"
